"""Scaffold a new repository's cldc policy configuration.

`cldc init` is the onboarding path: it writes a minimal
`.claude-compiler.yaml` that `extends:` one or more bundled presets,
and — if no `CLAUDE.md` exists — also writes a stub `CLAUDE.md` so
`cldc compile` can discover the repo. It never clobbers existing
files unless the caller passes `force=True`, and it never edits
`CLAUDE.md` once that file exists.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from cldc._logging import get_logger
from cldc.errors import CldcError
from cldc.presets import list_presets

logger = get_logger(__name__)

COMPILER_CONFIG_FILENAME = ".claude-compiler.yaml"
CLAUDE_MD_FILENAME = "CLAUDE.md"

_CLAUDE_MD_STUB = """# {repo_name}

This repository uses [`cldc`](https://github.com/AbdelStark/claude-md-compiler)
to compile its `CLAUDE.md` and `{config}` into a versioned policy
lockfile under `.claude/policy.lock.json`.

Policy rules live in `{config}` and are inherited from the bundled
preset(s) listed under `extends:`. Add repo-local rules inline below
in a fenced `cldc` block if you need something the preset does not
cover.

```cldc
rules: []
```
"""


_COMPILER_CONFIG_TEMPLATE = """# Generated by `cldc init`.
#
# `extends:` merges rules from bundled preset policy packs into this
# repo's compiled lockfile. Run `cldc preset list` to see every
# available pack and `cldc preset show NAME` to inspect one.
extends:
{extends_block}
# Add repo-local rules below. They compose with the preset rules
# listed above; duplicate rule IDs are a hard error.
rules: []
"""


class InitError(CldcError):
    """Raised when `cldc init` cannot scaffold the policy config."""


@dataclass(frozen=True)
class InitReport:
    """Deterministic outcome of a `cldc init` run.

    Every path in `created` or `updated` is recorded as a POSIX
    string relative to the initialized repo root. `skipped` lists
    files that already existed and were intentionally left alone.
    """

    repo_root: str
    presets: list[str]
    created: list[str]
    updated: list[str]
    skipped: list[str]
    next_action: str

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serializable dict with stable key ordering."""
        payload = asdict(self)
        return {key: payload[key] for key in ("repo_root", "presets", "created", "updated", "skipped", "next_action")}


def _validate_presets(names: list[str]) -> list[str]:
    if not names:
        raise InitError("at least one preset name is required; pass --preset or rely on the default")
    available = {preset.name for preset in list_presets()}
    deduped: list[str] = []
    seen: set[str] = set()
    for raw in names:
        name = (raw or "").strip()
        if not name:
            raise InitError("preset names must be non-empty strings")
        if name not in available:
            joined = ", ".join(sorted(available)) or "<none>"
            raise InitError(f"preset {name!r} is not bundled with this cldc version; available: {joined}")
        if name in seen:
            continue
        seen.add(name)
        deduped.append(name)
    return deduped


def _render_compiler_config(presets: list[str]) -> str:
    extends_block = "\n".join(f"  - {name}" for name in presets)
    return _COMPILER_CONFIG_TEMPLATE.format(extends_block=extends_block)


def _render_claude_md(repo_name: str) -> str:
    return _CLAUDE_MD_STUB.format(repo_name=repo_name, config=COMPILER_CONFIG_FILENAME)


def initialize_repo_policy(
    repo_root: Path | str,
    *,
    presets: list[str] | None = None,
    force: bool = False,
) -> InitReport:
    """Scaffold `.claude-compiler.yaml` (+ stub `CLAUDE.md`) for a repo.

    The target directory must exist. When `force` is false, an
    existing `.claude-compiler.yaml` causes an `InitError`. `CLAUDE.md`
    is never overwritten — if the file already exists, it is recorded
    as `skipped` regardless of `force`.
    """

    requested = presets if presets is not None else ["default"]
    normalized_presets = _validate_presets(requested)

    root = Path(repo_root).expanduser().resolve()
    if not root.exists():
        raise InitError(f"repo path does not exist: {root}")
    if not root.is_dir():
        raise InitError(f"repo path is not a directory: {root}")

    config_path = root / COMPILER_CONFIG_FILENAME
    claude_md_path = root / CLAUDE_MD_FILENAME

    created: list[str] = []
    updated: list[str] = []
    skipped: list[str] = []

    config_content = _render_compiler_config(normalized_presets)
    if config_path.exists():
        if not force:
            raise InitError(
                f"{COMPILER_CONFIG_FILENAME} already exists at {config_path}; pass force=True (or `--force` from the CLI) to overwrite it"
            )
        config_path.write_text(config_content, encoding="utf-8")
        updated.append(COMPILER_CONFIG_FILENAME)
        logger.debug("updated %s", config_path)
    else:
        config_path.write_text(config_content, encoding="utf-8")
        created.append(COMPILER_CONFIG_FILENAME)
        logger.debug("created %s", config_path)

    if claude_md_path.exists():
        skipped.append(CLAUDE_MD_FILENAME)
    else:
        claude_md_path.write_text(_render_claude_md(root.name or "repo"), encoding="utf-8")
        created.append(CLAUDE_MD_FILENAME)
        logger.debug("created %s", claude_md_path)

    return InitReport(
        repo_root=str(root),
        presets=normalized_presets,
        created=sorted(created),
        updated=sorted(updated),
        skipped=sorted(skipped),
        next_action=f"Run `cldc compile {root}` to build the lockfile from the new config.",
    )
